# Generated by Django 5.0.6 on 2024-06-14 18:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=255)),
                ('country', models.CharField(default='', max_length=255)),
                ('data_vendor', models.CharField(default='', max_length=255)),
                ('panel', models.CharField(default='', max_length=255)),
                ('panel_group', models.CharField(blank=True, default='', max_length=255)),
                ('scope_of_subscription', models.CharField(blank=True, default='', max_length=255)),
                ('data_type', models.CharField(default='', max_length=255)),
                ('granularity', models.CharField(default='national', max_length=255)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('current_update', models.DateTimeField(blank=True, null=True)),
                ('next_update', models.DateTimeField(blank=True, null=True)),
                ('data_upload', models.FileField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
            ],
        ),
    ]
