# Generated by Django 5.0.6 on 2024-06-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_sourcemodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcemodel',
            name='current_update',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sourcemodel',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sourcemodel',
            name='next_update',
            field=models.DateField(blank=True, null=True),
        ),
    ]
