# Generated by Django 5.0.6 on 2024-06-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_sourcemodel_current_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcemodel',
            name='current_update',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sourcemodel',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sourcemodel',
            name='next_update',
            field=models.DateField(blank=True, null=True),
        ),
    ]
