# Generated by Django 5.0.6 on 2024-06-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_sourcemodel_current_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcemodel',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
    ]
