# Generated by Django 5.0.6 on 2024-06-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_sourcemodel_granularity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcemodel',
            name='granularity',
            field=models.CharField(default='unduye', max_length=255),
        ),
    ]
