# Generated by Django 5.0.6 on 2024-06-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_sourcemodel_granularity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcemodel',
            name='current_update',
            field=models.DateField(blank=True, default='Unscheduled', null=True),
        ),
        migrations.AlterField(
            model_name='sourcemodel',
            name='next_update',
            field=models.DateField(blank=True, default='Unscheduled', null=True),
        ),
    ]
