# Generated by Django 5.0.6 on 2024-06-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_sourcemodel_current_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcemodel',
            name='current_status',
            field=models.CharField(default='Unscheduled', max_length=50),
        ),
        migrations.AddField(
            model_name='sourcemodel',
            name='next_status',
            field=models.CharField(default='Unscheduled', max_length=50),
        ),
        migrations.AlterField(
            model_name='sourcemodel',
            name='current_update',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sourcemodel',
            name='next_update',
            field=models.DateField(blank=True, null=True),
        ),
    ]
