# Generated by Django 5.0.6 on 2024-06-21 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_sourcemodel_current_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcemodel',
            name='status',
        ),
    ]
