# Generated by Django 5.0.6 on 2024-06-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_sourcemodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcemodel',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
    ]
