# Generated by Django 5.0.6 on 2024-06-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_sourcemodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcemodel',
            name='awaiting_status',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sourcemodel',
            name='delayed_status',
            field=models.CharField(default='delayed', max_length=50),
        ),
        migrations.AddField(
            model_name='sourcemodel',
            name='scheduled_status',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sourcemodel',
            name='next_status',
            field=models.CharField(default='unscheduled', max_length=50),
        ),
    ]
