# Generated by Django 5.0.6 on 2024-06-21 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_sourcemodel_awaiting_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sourcemodel',
            old_name='awaiting_status',
            new_name='datadelivery_status',
        ),
        migrations.RemoveField(
            model_name='sourcemodel',
            name='delayed_status',
        ),
        migrations.RemoveField(
            model_name='sourcemodel',
            name='scheduled_status',
        ),
    ]
